# Site Settings
title: Hybrid System Engineer
email: theodore@nextwe.xyz
description: Portfolio and blog of Theodore.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://leesuk-kim.github.io" # the base hostname & protocol for your site
google_analytics: "UA-96533362-1"

# User Settings
username: Leesuk Kim (Theodore)
user_description: System&Network Engineer, Arduino Engineer, Devops Engineer, Machine Learning Scientest
disqus_username: theodore-kim

# Social Media
# Remove the item if you don't need it
github_username: leesuk-kim
facebook_username: theodore.leesuk.kim
twitter_username: thdr_lees
instagram_username: thdr_lees
linkedin_username: leesukkim
# medium_username: medium_username

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/

# Plugins
gems:
  - jemoji

# Links to include in menu navigation
# For external links add external: true
links:
  - title: Home
    url: /
  - title: About
    url: /about/
  - title: Contact
    url: /contact/

# Exclude my node related stuff
exclude: ['package.json', 'src', 'node_modules']
